version: '3.8'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        container_name: xw-elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - path.repo=/usr/share/elasticsearch/backups
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - xw-esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - xw-stack-net
    kibana:
        image: docker.elastic.co/kibana/kibana:7.8.0
        container_name: xw-kibana
        environment:
            - elasticsearch.url=http://elasticsearch:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 5601:5601
        networks:
            - xw-stack-net
        depends_on:
            - elasticsearch
    
volumes:
    xw-esdata:
        driver: local

networks:
    xw-stack-net: