filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- copy_fields:
    fields:
        - from: container.labels.com_docker_compose_service
          to: app.name
    fail_on_error: false
    ignore_missing: true
- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.dashboards.enabled: true
setup.template.enabled: true
setup.kibana.host: "http://kibana:5601"

logging.to_files: false

xpack.monitoring:
  enabled: true
  elasticsearch: ~